name: saas-background-server

volumes:
  # region Cloud services
  pgdata:
  # endregion

networks:
  saas-background-server-network:
    driver: bridge
    attachable: true

  shared-network:
    external: true
    name: shared-network

services:  
  st-background-server:
    depends_on:
      st-bg-redis:
        condition: service_healthy
      st-bg-postgres:
        condition: service_healthy
    container_name: st-background-server
    restart: unless-stopped
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    env_file:
      - ../.env
    environment:
      - NODE_ENV=development
      - PORT=3001
    ports:
      - 3001:3001
    volumes:
      - ../src:/app/src
    command:
      - pnpm
      - dev
    networks:
      - saas-background-server-network

  # region Cloud services
  st-bg-redis:
    container_name: st-bg-redis
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - 6379:6379
    networks:
      - saas-background-server-network
      - shared-network

  st-bg-postgres:
    container_name: st-bg-postgres
    image: postgres:17
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: saas-background-server
      POSTGRES_USER: saas-bg-user
      POSTGRES_PASSWORD: saas-bg-password
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - saas-background-server-network  
  # endregion

